Revert "Remove obsolete `CAExcludePath`"
This reverts commit db74703d6ee40c8ed9b459c8ed07662fbbd9e0db.

It seems this is still needed. Without this setting the ARM builds fail with error:
> C:\a\nas2d-core\nas2d-core\vcpkg_installed\arm64-windows\arm64-windows\include\gtest\gtest-matchers.h(299): error C26439: This kind of function should not throw. Declare it 'noexcept' (f.6). [C:\a\nas2d-core\nas2d-core\test\test.vcxproj]
> C:\a\nas2d-core\nas2d-core\vcpkg_installed\arm64-windows\arm64-windows\include\gtest\gtest-matchers.h(304): error C26439: This kind of function should not throw. Declare it 'noexcept' (f.6). [C:\a\nas2d-core\nas2d-core\test\test.vcxproj]